MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'res_net'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        MIN_SIZES: [[15, 15], [45, 45], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[45, 45], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        FEATURE_MAPS: [[38, 63], [19, 32], [10, 16], [5, 8], [3, 4], [1, 2]]
        STRIDES: [[8, 8], [16, 16], [30, 31], [60, 63], [100, 125], [300, 250]]
INPUT:
    IMAGE_SIZE: [300, 500]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_scaled'
DATASET_DIR: "datasets"
MODEL_SAVE_STEP: 2000
EVAL_STEP: 10000 