MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'res_net'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 8 # NOTE CHANGED BATCH SIZE FROM 16 TO 8
    LR: 1e-3
    WEIGHT_DECAY: 5e-3 # INCREASED WEIGHT DECAY
OUTPUT_DIR: 'outputs/rdd2020_weight_decay_5e3_batch_size_8_data_augmentation'
DATASET_DIR: "datasets"
MODEL_SAVE_STEP: 2000
EVAL_STEP: 10000 
