MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'res_net'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]] #size of bounding boxes for each feature map
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        FEATURE_MAPS: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
        STRIDES: [[8,8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]] # set to image_size/feature_map_size
        #These are the ones I want
        #ASPECT_RATIOS : [[1.75], [1.3, 0.18, 0.5], [1.3, 0.18, 0.5], [1.3, 0.18, 0.5], [0.17, 0.5], [0.5]] # Individual aspect ratios for each layer
        ASPECT_RATIOS : [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-4
OUTPUT_DIR: 'outputs/rdd2020_test_delete'
DATASET_DIR: "datasets"
MODEL_SAVE_STEP: 2000
EVAL_STEP: 10000 
