MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'res_net'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        MIN_SIZES: [[5,5], [25, 25], [50, 50], [75, 75], [125, 125], [200, 200]] #size of bounding boxes for each feature map
        MAX_SIZES: [[25, 25], [50, 50], [75, 75], [125, 125], [200, 200], [315, 315]]
        FEATURE_MAPS: [[44, 82], [22, 41], [11, 21], [5, 10], [3, 6], [1, 2]]
        STRIDES: [[8,8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]] # set to image_size/feature_map_size
        #These are the ones I want
        #ASPECT_RATIOS : [[1.75], [1.3, 0.18, 0.5], [1.3, 0.18, 0.5], [1.3, 0.18, 0.5], [0.17, 0.5], [0.5]] # Individual aspect ratios for each layer
        #ASPECT_RATIOS : [[1.75], [1.3, 5], [1.3, 5], [1.3, 5], [2], [2]]
        ASPECT_RATIOS: [[3], [2, 4], [2, 4], [2, 4], [4], [3]]
INPUT:
    IMAGE_SIZE: [350,650]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/tdt4265_test'
DATASET_DIR: "datasets"