MODEL:
    NUM_CLASSES: 5
    THRESHOLD: 0.5
    BACKBONE:
        NAME: 'res_net'
        PRETRAINED: True
        OUT_CHANNELS: [128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        MIN_SIZES:  [[4, 8], [21, 37], [43, 75], [64, 112], [106, 188], [170, 300]]
        MAX_SIZES:  [[21, 37], [43, 75], [64, 112], [106, 188], [170, 300], [268, 472]]
        FEATURE_MAPS:  [[32, 57], [16, 29], [8, 15], [4, 8], [2, 4], [1, 3]]
        STRIDES:  [[8, 8], [16, 17], [32, 30], [64, 65], [128, 113], [255, 225]]
        ASPECT_RATIOS: [[5.29], [3.53, 7.06], [3.53, 7.06], [3.53, 7.06], [7.06], [5.29]]

INPUT:
    IMAGE_SIZE: [255, 450]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_255x450'
DATASET_DIR: "datasets"
MODEL_SAVE_STEP: 2000
EVAL_STEP: 5000 