MODEL:
    NUM_CLASSES: 5
    THRESHOLD: 0.5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [256, 512, 256, 256, 128, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        MIN_SIZES: [[15, 15], [45, 45], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[45, 45], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        FEATURE_MAPS: [[63, 38], [32, 19], [16, 10], [8, 5], [4, 3], [2, 1]]
        STRIDES: [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]

INPUT:
    IMAGE_SIZE: [500, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_experimentals'
DATASET_DIR: "datasets"