MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [256, 512, 256, 256, 128, 128]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS : [[75, 75], [38, 38], [19, 19], [10, 10], [5, 5], [3, 3]]
        STRIDES : [[16,16], [32, 32], [64, 64], [128, 128], [200, 200], [600, 600]]
        MIN_SIZES: [[30, 30], [90, 90], [222, 222], [324, 324], [426, 426], [528, 528]]
        MAX_SIZES: [[90, 90], [222, 222], [324, 324], [426, 426], [528, 528], [630,630]]

INPUT:
    IMAGE_SIZE: [600, 600]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 2e-3
OUTPUT_DIR: 'outputs/rdd2020_experimental'
DATASET_DIR: "/work/datasets"